src/Sinett/MLAB/BuilderBundle/Entity/Template.php
<?php
/*******************************************************************************************************************************
@copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
@license Proprietary and confidential
@author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)

Unauthorized copying of this file, via any medium is strictly prohibited

For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.
*******************************************************************************************************************************/

namespace Sinett\MLAB\BuilderBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Template
 */
class Template
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $description;

    /**
     * @var string
     */
    private $compatibleWith;

    /**
     * @var \Sinett\MLAB\BuilderBundle\Entity\App
     */
    private $app;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $groups;

    /**
     * zip file that is uploaded
     */
    private $zip_file;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $apps;
    
    /**
     * @var string
     */
    private $path;
    
    /**
     * @var boolean
     */
    private $enabled;
    
//flag used to see if it can be deleted or not
    private $canDelete;

    /**
     * @var string
     */
    private $group_names;
    

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->groups = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Template
     */
    public function setName($name)
    {
        $this->name = $name;
    
        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Template
     */
    public function setDescription($description)
    {
        $this->description = $description;
    
        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set compatibleWith
     *
     * @param string $compatibleWith
     * @return Template
     */
    public function setCompatibleWith($compatibleWith)
    {
        $this->compatibleWith = $compatibleWith;
    
        return $this;
    }

    /**
     * Get compatibleWith
     *
     * @return string 
     */
    public function getCompatibleWith()
    {
        return $this->compatibleWith;
    }

    /**
     * Set app
     *
     * @param \Sinett\MLAB\BuilderBundle\Entity\App $app
     * @return Template
     */
    public function setApp(\Sinett\MLAB\BuilderBundle\Entity\App $app = null)
    {
        $this->app = $app;
    
        return $this;
    }

    /**
     * Get app
     *
     * @return \Sinett\MLAB\BuilderBundle\Entity\App 
     */
    public function getApp()
    {
        return $this->app;
    }

    /**
     * Add groups
     *
     * @param \Sinett\MLAB\BuilderBundle\Entity\Group $groups
     * @return Template
     */
    public function addGroup(\Sinett\MLAB\BuilderBundle\Entity\Group $groups)
    {
        $this->groups[] = $groups;
    
        return $this;
    }

    /**
     * Remove groups
     *
     * @param \Sinett\MLAB\BuilderBundle\Entity\Group $groups
     */
    public function removeGroup(\Sinett\MLAB\BuilderBundle\Entity\Group $groups)
    {
        $this->groups->removeElement($groups);
    }

    /**
     * Get groups
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getGroups()
    {
        return $this->groups;
    }
    
    /**
     * Get display value
     *
     * @return \String
     */
    public function __toString()
    {
    	return $this->name;
    }
    
    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setZipFile(UploadedFile $zip_file = null)
    {
    	$this->zip_file = $zip_file;
    }
    
    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getZipFile()
    {
    	return $this->zip_file;
    }
    
    /**
     * Set path
     *
     * @param string $path
     * @return Template
     */
    public function setPath($path)
    {
        $this->path = $path;
    
        return $this;
    }

    /**
     * Get path
     *
     * @return string 
     */
    public function getPath()
    {
        return $this->path;
    }
    
    /**
     * calculate the path of this app, using the starting path from the parameter which = mlab:paths:app parameter setting
     *
     * @param string $start_path
     * @return App
     */
    public function calculateFullPath($start_path)
    {
    	return $start_path . $this->getPath() . "/" ;
    }
    

    /**
     * Set enabled
     *
     * @param boolean $enabled
     * @return Template
     */
    public function setEnabled($enabled)
    {
        $this->enabled = $enabled;
    
        return $this;
    }

    /**
     * Get enabled
     *
     * @return boolean 
     */
    public function getEnabled()
    {
        return $this->enabled;
    }
    /**
     * @var float
     */
    private $version;


    /**
     * Set version
     *
     * @param float $version
     * @return Template
     */
    public function setVersion($version)
    {
        $this->version = $version;
    
        return $this;
    }

    /**
     * Get version
     *
     * @return float 
     */
    public function getVersion()
    {
        return $this->version;
    }
    
    /**
     * Add apps
     *
     * @param \Sinett\MLAB\BuilderBundle\Entity\App $apps
     * @return Template
     */
    public function addApp(\Sinett\MLAB\BuilderBundle\Entity\App $apps)
    {
        $this->apps[] = $apps;
    
        return $this;
    }

    /**
     * Remove apps
     *
     * @param \Sinett\MLAB\BuilderBundle\Entity\App $apps
     */
    public function removeApp(\Sinett\MLAB\BuilderBundle\Entity\App $apps)
    {
        $this->apps->removeElement($apps);
    }

    /**
     * Get apps
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getApps()
    {
        return $this->apps;
    }
    
    /**
     * Returns all properties as an array
     */
    public function getArray() {
    	return array(
    			'id' => $this->id,
    			'name' => $this->name,
    			'path' => $this->path,
    			'description' => $this->description,
    			'version' => $this->version,
    			'groups' => $this->groups,
    			'enabled' => $this->enabled
    	);
    }    
    
    /**
     * Set can_delete
     *
     * @param string $name
     * @return Template
     */
    public function setCanDelete($canDelete)
    {
        $this->canDelete = $canDelete;
    
        return $this;
    }

    /**
     * Get can_delete
     *
     * @return string 
     */
    public function getCanDelete()
    {
        return $this->canDelete;
    }
    
    /**
     * Set enabled
     *
     * @param string $enabled
     * @return Component
     */
    public function setGroupNames($names)
    {
        $this->group_names = $names;
    
        return $this;
    }

    /**
     * Get group_names
     *
     * @return string 
     */
    public function getGroupNames()
    {
        return $this->group_names;
    }
    
}

src/Sinett/MLAB/BuilderBundle/Resources/views/Template/edit.html.twig
{#
@copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
@license Proprietary and confidential
@author Cecilie Jackbo Gran/Sinett 3.0 programme (firstname.middlename.lastname@ffi.no)
@author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)

Unauthorized copying of this file, via any medium is strictly prohibited 

For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.
#}
{% extends app.request.xmlHttpRequest ? '::ajax.html.twig' : '::base.html.twig' %}

{% block body -%}
	<h4>{% trans %}app.admin.templates.edit.groups.heading{% endtrans %}</h4>

    {{ form(edit_form) }}

{% endblock %}

src/Sinett/MLAB/BuilderBundle/Resources/views/Template/edit_admin.html.twig
{#
@copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
@license Proprietary and confidential
@author Cecilie Jackbo Gran/Sinett 3.0 programme (firstname.middlename.lastname@ffi.no)
@author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)

Unauthorized copying of this file, via any medium is strictly prohibited 

For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.
#}
{% extends app.request.xmlHttpRequest ? '::ajax.html.twig' : '::base.html.twig' %}

{% block body -%}
    <h5>{% trans %}app.admin.templates.tooltip.group{% endtrans %} {{ entity.name }}</h5>

    <form action="{{ path('template_update_group',  { 'template_id': template_id }) }}" method="post">
        
        {% for group in groups %}
            <input type="checkbox" class="mlab_edit_compgroup_checkbox" id="sinett_mlab_builderbundle_templategroup_{{ group.id }}_enabled" name="sinett_mlab_builderbundle_templategroup[{{ group.id }}][enabled]" value="{{ group.id }}" {% if group.isEnabled == "true" %} checked {% endif %}>
            <label class="mlab_edit_compgroup_checkbox_label" for="sinett_mlab_builderbundle_templategroup_{{ group.id }}_enabled">{{ group.name }}</label> 
            <br>
        {% endfor %}
            <br>
            <input type="submit" value="{% trans %}app.admin.components.new.create.button{% endtrans %}">
    </form>
   

{% endblock %}

src/Sinett/MLAB/BuilderBundle/Resources/views/Template/index.html.twig
{#
@copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
@license Proprietary and confidential
@author Cecilie Jackbo Gran/Sinett 3.0 programme (firstname.middlename.lastname@ffi.no)
@author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)

Unauthorized copying of this file, via any medium is strictly prohibited 

For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.
#}
{% extends app.request.xmlHttpRequest ? '::ajax.html.twig' : '::base.html.twig' %}

{% block body -%}

    <table class="records_list" id="table_template">
        <thead>
            <tr>
                <th>{% trans %}app.admin.templates.name{% endtrans %}</th>
                <th>{% trans %}app.admin.templates.version{% endtrans %}</th>
                <th>{% trans %}app.admin.templates.description{% endtrans %}</th>
                <th>{% trans %}app.admin.templates.groups{% endtrans %}</th>  
                {% if is_granted("ROLE_SUPER_ADMIN") %} <!-- Show this column only for ROLE_SUPER_ADMIN  -->
                    <th>{% trans %}app.admin.templates.enabled{% endtrans %}</th>
                    <th class="mlab_min_width_short"> 
                        <a class="mlab_button_new_template" href="{{ path('template_new') }}" title="{% trans %}app.admin.templates.tooltip.new{% endtrans %}"></a>
                    </th>              
                {% endif %}
            </tr>
        </thead>
        <tbody>
        {% for entity in entities %}
        	{{ include( 'SinettMLABBuilderBundle:Template:show.html.twig', { 'entity': entity } ) }}
        {% endfor %}
        </tbody>
    </table>
    {% endblock %}

src/Sinett/MLAB/BuilderBundle/Resources/views/Template/new.html.twig
{#
@copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
@license Proprietary and confidential
@author Cecilie Jackbo Gran/Sinett 3.0 programme (firstname.middlename.lastname@ffi.no)
@author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)

Unauthorized copying of this file, via any medium is strictly prohibited 

For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.
#}
{% extends app.request.xmlHttpRequest ? '::ajax.html.twig' : '::base.html.twig' %}

{% block body -%}
	<h4>{% trans %}app.admin.templates.new.heading{% endtrans %}</h4>

    {{ form(form) }}

{% endblock %}

src/Sinett/MLAB/BuilderBundle/Resources/views/Template/show.html.twig
{#
@copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
@license Proprietary and confidential
@author Cecilie Jackbo Gran/Sinett 3.0 programme (firstname.middlename.lastname@ffi.no)
@author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)

Unauthorized copying of this file, via any medium is strictly prohibited 

For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.
#}
<tr id="row_template_{{ entity.id }}">

    <td>{{ entity.name }}</td>
    <td class="mlab_align_center">{% if entity.version == null %} 1 {% else %}{{ entity.version }}{% endif %} </td>
    <td class="mlab_max_width_long">{{ entity.description }}</td>
    <td class="mlab_max_width_medium">
        <a href="{{ path('template_edit', { 'id': entity.id }) }}" title="{% trans %}app.admin.templates.tooltip.group{% endtrans %} '{{ entity.name }}'">
            {% if entity.groupNames is empty %} <!-- If no group -->
               {% trans %}app.admin.components.no.group{% endtrans %}
            {% else %} <!-- If have groups -->
                {{ entity.groupNames|raw }}
            {% endif %} 
        </a>
    </td>
    {% if is_granted("ROLE_SUPER_ADMIN") %} <!-- Show this column only for ROLE_SUPER_ADMIN  -->
        <td class="mlab_align_center">
            <a href="{{ path('template_toggle_state', { 'id': entity.id }) }}" class="mlab_icon_{{ entity.enabled == true ? "enabled" : "disabled" }}" ></a>
        </td>
        <td>
            {% if entity.canDelete %}
                <a href="{{ path('template_delete', { 'id': entity.id }) }}" class="mlab_icon_delete" title="{% trans %}app.admin.templates.tooltip.delete{% endtrans %} '{{ entity.name }}'"></a>
            {% endif %}
        </td>
    {% endif %}

</tr>